baseURL = "https://acejune.github.io/blog/"
defaultContentLanguage = "en"   # [en, zh-cn, fr, ...] determines default content language
languageCode = "en"             # language code
title = "June's Blog"

theme = "DoIt"    # Change the default theme to be use when building the site with Hugo



# ==============================================================================
#  Author config
# ==============================================================================
[author]
  name = "June"
  email = "junehanchoi@gmail.com"
  link = "https://acejune.github.io/"
  avatar = "/images/profile.jpeg"
  gravatarEmail = ""



# ==============================================================================
#  params
# ==============================================================================
[params]
  version = "0.3.X"                                 # DoIt theme version
  title = "june.log"                                # website title
  description = "This is June's blog"               # site description
  keywords = ["Machine Learning", "Data Science"]   # site keywords
  defaultTheme = "auto"                             # site default theme ("light", "dark", "black", "auto")
  gitRepo = ""                                      # public git repo url only then enableGitInfo is true
  fingerprint = ""                                  # which hash function used for SRI, when empty, no SRI is used ("sha256", "sha384", "sha512", "md5")
  dateFormat = "2006-01-02"                         # date format
  images = ["/images/profile.jpeg"]                 # website images for Open Graph and Twitter Cards
  enablePWA = false                                 # enable PWA support


  #####################
  #   Search config   #
  #####################
  [params.search]
    enable = true
    type = "fuse"           # type of search engine ("algolia", "fuse")
    contentLength = 4000    # max index length of the chunked content
    placeholder = ""        # placeholder of the search bar
    maxResultLength = 10    #  max number of results length
    snippetLength = 30      #  snippet length of the result
    highlightTag = "em"     #  HTML tag name of the highlight part in results
    absoluteURL = false     #  whether to use the absolute URL based on the baseURL in search index

    [params.search.fuse]
      #  https://fusejs.io/api/options.html
      isCaseSensitive = false
      minMatchCharLength = 2
      findAllMatches = false
      location = 0
      threshold = 0.3
      distance = 100
      ignoreLocation = false
      useExtendedSearch = false
      ignoreFieldNorm = false


  #####################
  #   Header config   #
  #####################
  [params.header]
    desktopMode = "fixed"         # desktop header mode ("fixed", "normal", "auto")
    mobileMode = "auto"           # mobile header mode ("fixed", "normal", "auto")
    themeChangeMode = "select"    # theme change mode ("switch", "select")
    
    # Header title config
    [params.header.title]
      logo = ""             # URL of the LOGO
      name = "june.log"     # title name
      pre = "🍕"            # you can add extra information before the name (HTML format is supported), such as icons
      post = ""             # you can add extra information after the name (HTML format is supported), such as icons
      typeit = true         #  whether to use typeit animation for title name


  #####################
  #   Footer config   #
  #####################
  [params.footer]
    enable = true
    custom = ''         # Custom content (HTML format is supported)
    hugo = false        # whether to show Hugo and theme info
    hostedOn = '<a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>'  # Hosted on (HTML format is supported)
    copyright = true    #  whether to show copyright info
    author = true       #  whether to show the author
    since = 2023        # Site creation time
    icp = ""            # ICP info only in China (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'    # license info (HTML format is supported)


  #######################################
  #   Section (all posts) page config   #
  #######################################
  [params.section]
    paginate = 20             # special amount of posts in each section page
    dateFormat = "01-02"      # date format (month and day)
    rss = 10                  # amount of RSS pages

    # recently updated posts settings
    [params.section.recentlyUpdated]
      enable = false
      rss = false
      days = 30
      maxCount = 10


  ##########################################
  #   List (category or tag) page config   #
  ##########################################
  [params.list]
    paginate = 20           # special amount of posts in each list page
    dateFormat = "01-02"    # date format (month and day)
    rss = 10                # amount of RSS pages


  ########################
  #   Home page config   #
  ########################
  [params.home]
    rss = 10    # amount of RSS pages

    # Home page profile
    [params.home.profile]
      enable = true
      gravatarEmail = ""                    # Gravatar Email for preferred avatar in home page
      avatarURL = "/images/profile.jpeg"    # URL of avatar shown in home page
      title = "June"                        # title shown in home page (HTML format is supported)
      subtitle = "넘버원(NO.1)이 아니라 온리원(Only One)이 되자!"      # subtitle shown in home page
      typeit = true                         # whether to use typeit animation for subtitle
      social = true                         # whether to show social links
      disclaimer = ""                       # disclaimer (HTML format is supported)
    
    # Home page posts
    [params.home.posts]
      enable = true
      paginate = 6                        # special amount of posts in each home posts page
      defaultHiddenFromHomePage = false   # replaced with hiddenFromHomePage in params.page


  ######################################
  #   Social config about the author   #
  ######################################
  [params.social]
    GitHub = "acejune"
    Linkedin = ""
    Twitter = ""
    Instagram = ""
    Facebook = ""
    Email = "junehanchoi@gmail.com"
    RSS = false


  ###################
  #   Page config   #
  ###################
  [params.page]
    hiddenFromHomePage = false    # whether to hide a page from home page
    hiddenFromSearch = false      # whether to hide a page from search results
    twemoji = false               # whether to enable twemoji
    lightgallery = false          # whether to enable lightgallery
    ruby = true                   # whether to enable the ruby extended syntax
    fraction = true               # whether to enable the fraction extended syntax
    fontawesome = true            # whether to enable the fontawesome extended syntax
    linkToMarkdown = true         # whether to show link to Raw Markdown content of the content
    linkToSource = false          # configure the link to the source file of the post
    linkToEdit = false            # configure the link to edit the post
    linkToReport = false          # configure the link to report issue for the post
    rssFullText = false           # whether to show the full text content in RSS
    pageStyle = "normal"          # page layout style ("normal", "wide")
    seriesNavigation = true       # whether to enable series navigation

    # outdated article reminder config
    [params.page.outdatedArticleReminder]
      enable = false
      reminder = 90   # Display the reminder if the last modified time is more than 90 days ago.
      warning = 180   # Display warning if the last modified time is more than 180 days ago.
    
    # Table of the contents config
    [params.page.toc]
      enable = true       # whether to enable the table of the contents
      keepStatic = false  # whether to keep the static table of the contents in front of the post
      auto = true         # whether to make the table of the contents in the sidebar automatically collapsed
    
    # KaTeX mathematical formulas
    [params.page.math]
      enable = true
      blockLeftDelimiter = ""     # default block delimiter is $$ ... $$ and \\[ ... \\]
      blockRightDelimiter = ""
      inlineLeftDelimiter = ""    # default inline delimiter is $ ... $ and \\( ... \\)
      inlineRightDelimiter = ""
      copyTex = false             # KaTeX extension copy_tex
      mhchem = true               # KaTeX extension mhchem
    
    # Code config
    [params.page.code]
      copy = true           # whether to show the copy button of the code block
      maxShownLines = 10    # the maximum number of lines of displayed code by default
    
    # Table config
    [params.page.table]
      sort = false   # whether to enable sorting in the tables

    # social share links in post page
    [params.page.share]
      enable = false
      Twitter = true
      Facebook = true
      Linkedin = false

    # Comment config
    [params.page.comment]
      enable = true

      # Utterances comment config
      [params.page.comment.utterances]
        enable = true
        repo = "acejune/blog-comment"   # owner/repo
        issueTerm = "pathname"
        label = ""
        lightTheme = "github-light"
        darkTheme = "github-dark"


  ######################
  #   Sponsor config   #
  ######################
  [params.sponsor]
    enable = false
    bio = "If you find this post helpful, please consider sponsoring."
    link = "https://www.buymeacoffee.com" # The link to your sponsor page
    custom = ""   # Custom HTML button


  #####################
  #   TypeIt config   #
  #####################
  [params.typeit]
    speed = 100           # typing speed between each step (measured in milliseconds)
    cursorSpeed = 1000    # blinking speed of the cursor (measured in milliseconds)
    cursorChar = "|"      # character used for the cursor (HTML format is supported)
    duration = -1         # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)


  ########################
  #   Analytics config   #
  ########################
  [params.analytics]
    enable = true

    # Google Analytics
    [params.analytics.google]
      id = "G-WZ6YNQXK01"
      anonymizeIP = true    # whether to anonymize IP



# ==============================================================================
#  menu
# ==============================================================================
[menu]
  [[menu.main]]
    identifier = "posts"
    pre = "📝"      # you can add extra information before the name (HTML format is supported), such as icons
    post = ""       # you can add extra information after the name (HTML format is supported), such as icons
    name = "Posts"
    url = "/posts/"
    title = ""      # title will be shown when you hover on this menu link
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = "🏷️"
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "about"
    pre = "🧑‍🦱"
    post = ""
    name = "About"
    url = "https://acejune.github.io/"
    title = ""
    weight = 4



# ==============================================================================
#  Markup related config in Hugo
# ==============================================================================
[markup]

  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    noClasses = false  # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
